Repository javascript-tutorial/id.javascript.info, pull requests merged in 2019-12, with the labels that each got.

#53 Arrow functions, the basics
  1-js/02-first-steps/16-arrow-functions-basics/article.md
Labels: needs +1

#56 Symbol type
  1-js/04-object-basics/03-symbol/article.md
Labels: needs +1

#57 Object methods, "this"
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#58 Object to primitive conversion
  1-js/04-object-basics/05-object-toprimitive/article.md
Labels: needs +1

#59 Constructor, operator "new"
  1-js/04-object-basics/06-constructor-new/article.md
Labels: ready to merge

#60 JSON Methods, toJSON (task and solution)
  1-js/05-data-types/12-json/1-serialize-object/task.md
  1-js/05-data-types/12-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/12-json/2-serialize-event-circular/task.md
Labels: needs +1

#61 Object methods, "this" (task and solution)
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/2-check-syntax/task.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/task.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
Labels: needs +1, ready to merge

#62 Constructor, operator "new" (task and solution)
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/task.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
Labels: needs +1

#63 Arrays
  1-js/05-data-types/04-array/article.md
Labels: ready to merge

#64 Arrays (task and solution)
  1-js/05-data-types/04-array/1-item-value/solution.md
  1-js/05-data-types/04-array/1-item-value/task.md
  1-js/05-data-types/04-array/10-maximal-subarray/solution.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/task.md
Labels: needs +1, ready to merge

#66 Destructuring assignment
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#67 Numbers
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#68 translate closure
  1-js/06-advanced-functions/03-closure/1-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/1-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/2-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/3-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/4-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/6-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/7-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/8-make-army/solution.md
  1-js/06-advanced-functions/03-closure/8-make-army/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1
