Repository javascript-tutorial/id.javascript.info, pull requests merged in 2020-10, with the labels that each got.

#111 Translate Class basic syntax
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#113 Promises chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
Labels: needs +1

#114 Private and protected properties and methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1

#115 Update article.md
  8-web-components/1-webcomponents-intro/article.md
Labels: needs +1

#116 Static properties and methods
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#120 Promise API
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#121 Promisify
  1-js/11-async/06-promisify/article.md
Labels: needs +1

#122 Microtask queue
  1-js/11-async/07-microtask-queue/article.md
Labels: needs +1

#123 Translate Dynamic Imports
  1-js/13-modules/03-modules-dynamic-imports/article.md
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
  1-js/13-modules/03-modules-dynamic-imports/say.view/say.js
Labels: needs +1

#125 Class inheritance
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/source.view/index.html
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: changes requested

#124 Update article and tips on the README
  2-ui/1-document/01-browser-environment/article.md
  README.md
Labels: needs +1

#118 Error Handling With Promises
  1-js/11-async/04-promise-error-handling/01-error-async/solution.md
  1-js/11-async/04-promise-error-handling/01-error-async/task.md
  1-js/11-async/04-promise-error-handling/article.md
Labels: needs +1

#126 Class checking: "instanceof"
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
Labels: needs +1

#127 (i18n-id): translate article of modules/import-export into Indonesian
  1-js/13-modules/02-import-export/article.md
Labels: needs +1

#128 Mixins
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
  1-js/09-classes/index.md
Labels: needs +1

#129 Async/Await
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
Labels: needs +1

#132 (i18n-id): translate article of network/formdata into Indonesian
  5-network/02-formdata/article.md
Labels: review needed

#135 menghapus merge conflict
  1-js/11-async/02-promise-basics/article.md
Labels: needs +1

#133 Custom errors, extending Error
  1-js/10-error-handling/2-custom-errors/1-format-error/task.md
  1-js/10-error-handling/2-custom-errors/article.md
  1-js/10-error-handling/index.md
Labels: hacktoberfest-accepted, needs +1

#138 Eval: run a code string
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
Labels: review needed

#137 (i18n-id) translate article.md of network/fetch-progress into indonesian
  5-network/03-fetch-progress/article.md
Labels: needs +1

#140 Currying
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#139 Custom Elements - Elemen Kustom
  8-web-components/2-custom-elements/1-live-timer/solution.md
  8-web-components/2-custom-elements/1-live-timer/task.md
  8-web-components/2-custom-elements/article.md
Labels: needs +1

#134 Fetch
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
Labels: needs +1

#141 Async iteration and generators
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
  1-js/12-generators-iterators/index.md
Labels: hacktoberfest-accepted, needs +1

#142 (i18n) translate article of network/fetch-abort into indonesian
  5-network/04-fetch-abort/article.md
Labels: needs +1

#144 The old "var"
  1-js/06-advanced-functions/04-var/article.md
Labels: needs +1

#143 Shadow DOM
  8-web-components/3-shadow-dom/article.md
Labels: review needed

#151 Penambahan glossary
  glossary.md
Labels: review needed

#152 Updating readme
  README.md
Labels: review needed

#153 update glossary
  glossary.md
Labels: review needed

#154 Update glossray
  glossary.md
Labels: review needed

#145 Fetch: Cross-Origin Requests
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
Labels: needs +1

#147 translate 1-try-catch :rocket:
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
Labels: needs +1

#148 Template Element - Elemen Template
  8-web-components/4-template-element/article.md
Labels: needs +1

#149 Popups and window methods
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1

#157 Form properties and methods
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#158 Shadow DOM and Events
  8-web-components/7-shadow-dom-events/article.md
Labels: needs +1
